# Generated by Django 3.1.5 on 2021-03-08 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='picture')),
                ('name', models.CharField(max_length=100)),
                ('sub', models.TextField()),
                ('desc', models.TextField()),
                ('month', models.CharField(max_length=100)),
                ('date', models.IntegerField()),
            ],
        ),
    ]
