# Generated by Django 3.1.5 on 2021-04-16 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='sub',
        ),
    ]
